server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway   #暴露名称

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com    #在注册中心的实例名
    prefer-ip-address: true          #允许点击查看信息


info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  prefix: /daodao                  #前缀
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**         #代替 真实微服务的暴露名称


